### ISSUE TITLE
BungeeCord 支持

### ISSUE THREAD

**Issue by GamerNoTitle** [AnzhiZhang/ChatHub#1]
好像不支持BungeeCord？我的版本是BungeeCord 4.4.2
```
➜  plugins ls
bStats  ChatHub-1.0.0.jar  viabackwards  ViaBackwards  viarewind  ViaRewind  viaversion  ViaVersion  ViaVersion-4.2.1.jar.bak  ViaVersion-4.4.2.jar
➜  plugins cd ..
➜  bungeecord ls
BungeeCord      config.yml  locations.yml  modules      plugins      start.sh                velocity-3.1.1-98.jar.bak        velocity.toml
BungeeCord.jar  lang        logs           modules.yml  proxy.log.0  velocity-1.1.8.jar.bak  velocity-3.1.2-SNAPSHOT-137.jar
➜  bungeecord ./start.sh          
*** Warning, this build is outdated ***
*** Please download a new build from http://ci.md-5.net/job/BungeeCord ***
*** You will get NO support regarding this build ***
*** Server will start in 10 seconds ***
11:12:27 [INFO] Using mbed TLS based native cipher.
11:12:27 [INFO] Using zlib based native compressor.
11:12:27 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:862bb2a:1636
11:12:27 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
11:12:27 [INFO] Epoll is working, utilising it!
11:12:28 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())

11:12:28 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())

11:12:28 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())

11:12:28 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())

11:12:28 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())

11:12:28 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())

11:12:28 [WARNING] Could not load plugin from file plugins/ChatHub-1.0.0.jar
java.lang.NullPointerException: Plugin must have a plugin.yml or bungee.yml
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
    at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:380)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:269)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
11:12:28 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:28 [INFO] Loaded plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:28 [WARNING] [ViaVersion]       / \
11:12:28 [WARNING] [ViaVersion]      /   \
11:12:28 [WARNING] [ViaVersion]     /  |  \
11:12:28 [WARNING] [ViaVersion]    /   |   \         BUNGEECORD IS OUTDATED
11:12:28 [WARNING] [ViaVersion]   /         \   VIAVERSION MAY NOT WORK AS INTENDED
11:12:28 [WARNING] [ViaVersion]  /     o     \
11:12:28 [WARNING] [ViaVersion] /_____________\
11:12:28 [INFO] Loaded plugin ViaVersion version 4.4.2 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
11:12:28 [INFO] Loaded plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:28 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:28 [INFO] Loaded plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:28 [INFO] Loaded plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:28 [WARNING] Forced host server pvp is not defined
11:12:28 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:28 [INFO] Enabled plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:28 [INFO] [ViaVersion] Loading 1.12 -> 1.13 mappings...
11:12:29 [INFO] [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
11:12:29 [INFO] [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
11:12:29 [INFO] [ViaVersion] Loading 1.14 -> 1.15 mappings...
11:12:29 [INFO] [ViaVersion] Loading 1.15 -> 1.16 mappings...
11:12:29 [INFO] [ViaVersion] Loading block connection mappings ...
11:12:29 [INFO] [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
11:12:30 [INFO] [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
11:12:30 [INFO] [ViaVersion] Loading 1.17 -> 1.18 mappings...
11:12:30 [INFO] [ViaVersion] Loading 1.18 -> 1.19 mappings...
11:12:30 [INFO] Enabled plugin ViaVersion version 4.4.2 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
11:12:30 [INFO] Enabled plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:30 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:30 [INFO] Enabled plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:30 [INFO] Enabled plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
11:12:30 [INFO] [ViaVersion] ViaVersion detected lowest supported version by the proxy: 1.8.x (47)
11:12:30 [INFO] [ViaVersion] Highest supported version by the proxy: 1.18.2 (758)
11:12:31 [INFO] Listening on /0.0.0.0:44660
11:12:31 [WARNING] [ViaVersion] There is a newer plugin version available: 4.5.1, you're on: 4.4.2
11:12:31 [INFO] Started query on /[0:0:0:0:0:0:0:0%0]:44660
11:12:31 [INFO] [ViaVersion] Finished mapping loading, shutting down loader executor!
>chathub
11:12:34 [INFO] Command not found
>>/chathub
11:12:36 [INFO] Command not found
```

**Comment by XiaoHuiHui233** [comment]
为什么你会觉得一个VC的插件会支持BC

**Comment by GamerNoTitle** [comment]
> 为什么你会觉得一个VC的插件会支持BC

Via系列是两个都支持的 :D

**Comment by AnzhiZhang** [comment]
BC 请用 [ChatHub](https://github.com/CreatioStudio/ChatHub)，不提供维护
